# Generated by Django 4.2.9 on 2024-02-05 07:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="follower_on",
            field=models.ManyToManyField(
                related_name="follower_on",
                to=settings.AUTH_USER_MODEL,
                verbose_name="подписки",
            ),
        ),
    ]
